<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Authors>Dakari</Authors>
        <Version>1.6.0</Version>
        <Copyright>Dakari</Copyright>
        <Description>Fixes issues in Priconne that get caused by XUAT</Description>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(GameDir)\BepInEx\interop\Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="XUnity.AutoTranslator.Plugin.Core" Publicize="True">
            <HintPath>$(GameDir)\BepInEx\plugins\XUnity.AutoTranslator\XUnity.AutoTranslator.Plugin.Core.dll</HintPath>
        </Reference>
        <Reference Include="ExIni" Publicize="True">
            <HintPath>$(GameDir)\BepInEx\plugins\XUnity.AutoTranslator\ExIni.dll</HintPath>
        </Reference>
        <Reference Include="XUnity.Common">
            <HintPath>$(GameDir)\BepInEx\core\XUnity.Common.dll</HintPath>
        </Reference>
        <Reference Include="SugoiOfflineTranslator">
            <HintPath>$(GameDir)\BepInEx\plugins\XUnity.AutoTranslator\Translators\SugoiOfflineTranslator.dll</HintPath>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>$(GameDir)\BepInEx\core\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx.Core"> 
            <HintPath>$(GameDir)\BepInEx\core\BepInEx.Core.dll</HintPath> 
        </Reference>
        <Reference Include="BepInEx.Unity.IL2CPP">
            <HintPath>$(GameDir)\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Common">
            <HintPath>$(GameDir)\BepInEx\core\Il2CppInterop.Common.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Generator">
            <HintPath>$(GameDir)\BepInEx\core\Il2CppInterop.Generator.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.HarmonySupport">
            <HintPath>$(GameDir)\BepInEx\core\Il2CppInterop.HarmonySupport.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Runtime">
            <HintPath>$(GameDir)\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem">
            <HintPath>$(GameDir)\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
        </Reference>
        
        <Reference Include="UnityEngine.AnimationModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.AnimationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.AudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DirectorModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.DirectorModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GameCenterModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.GameCenterModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GridModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.GridModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.InputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.JSONSerializeModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.JSONSerializeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ParticleSystemModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.ParticleSystemModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Physics2DModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.Physics2DModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ScreenCaptureModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.ScreenCaptureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SharedInternalsModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.SharedInternalsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteShapeModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.SpriteShapeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubsystemsModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.SubsystemsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.TerrainModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.TextRenderingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TilemapModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.TilemapModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIElementsNativeModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.UIElementsNativeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.UIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.UnityAnalyticsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.UnityWebRequestModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VFXModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.VFXModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VideoModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.VideoModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VRModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.VRModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.XRModule">
            <HintPath>$(GameDir)\BepInEx\interop\UnityEngine.XRModule.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Fastenshtein" Version="1.0.0.8" />
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all" />
    </ItemGroup>

    <Target Name="CopyToGameDir" AfterTargets="AfterBuild">
        <!-- Collect all defined GameDir properties into an item group -->
        <ItemGroup>
            <GameDirList Include="$(GameDir)" Condition="'$(GameDir)' != ''" />
            <GameDirList Include="$(GameDir2)" Condition="'$(GameDir2)' != ''" />
            <GameDirList Include="$(GameDir3)" Condition="'$(GameDir3)' != ''" />
            <GameDirList Include="$(GameDir4)" Condition="'$(GameDir4)' != ''" />
            <GameDirList Include="$(GameDir5)" Condition="'$(GameDir5)' != ''" />
            <GameDirList Include="$(GameDir6)" Condition="'$(GameDir6)' != ''" />
            <GameDirList Include="$(GameDir7)" Condition="'$(GameDir7)' != ''" />
            <GameDirList Include="$(GameDir8)" Condition="'$(GameDir8)' != ''" />
            <GameDirList Include="$(GameDir9)" Condition="'$(GameDir9)' != ''" />
            <GameDirList Include="$(GameDir10)" Condition="'$(GameDir10)' != ''" />
        </ItemGroup>
        
        <!-- Copy DLL and PDB to each game directory using batching -->
        <Copy SourceFiles="$(OutDir)$(AssemblyName).dll" DestinationFolder="%(GameDirList.Identity)\BepInEx\plugins" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(OutDir)$(AssemblyName).pdb" DestinationFolder="%(GameDirList.Identity)\BepInEx\plugins" SkipUnchangedFiles="true" />
        
        <!-- Display message for each directory -->
        <Message Text="Copied $(AssemblyName).dll to: %(GameDirList.Identity)" Importance="high" />
    </Target>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
        <Exec Command="powershell -ExecutionPolicy Bypass -File UpdateVersion.ps1" />
    </Target>


</Project>
